dataset_name: birdset
split: PER
export_path: gs://representation-learning/resampler-project/birdset/v0.1.0/audio
target_sr: 16000
resampler:
  backend: librosa
  res_type: kaiser_best
  scale: true
  fix: true
max_workers: 8
skip_existing: true
