nfs:
  dataset:
    dataset_name: beans
    split: validation
    sample_rate: 16000
    data_root: /home/milad_earthspecies_org/data-migration/marius-highmem/mnt/foundation-model-data/audio_16k/

bucket:
  dataset:
    dataset_name: beans
    split: validation
    sample_rate: 16000
    data_root: gs://esp-ml-datasets/beans/v0.1.0/raw/
