# Benchmark configuration for job array experiments

nfs:
  dataset:
    dataset_name: beans
    split: cbi_train
    sample_rate: 44100 # if you want to resample, keep this line and set to desired rate else remove this line to avoid resampling
    data_root: /home/milad_earthspecies_org/data-migration/marius-highmem/mnt/foundation-model-data/

bucket:
  dataset:
    dataset_name: beans
    split: cbi_train
    sample_rate: 44100 # if you want to resample, keep this line and set to desired rate else remove this line to avoid resampling
    data_root: gs://esp-ml-datasets/beans/v0.1.0/raw/
