"""Curated list of iconic, famously well-described animal vocalizations.

Each entry maps a scientific binomial (matching the GBIF-backbone
``canonical_name`` used by the Xeno-canto / iNaturalist adapters and the
BirdCODE prediction ``Species`` field) to a distinctive, purely *acoustic*
description of the sound the animal makes. These descriptions are written to
be discriminable from one another so they can serve as multiple-choice
options: the correct option is the description of the focal species, and the
negatives are real descriptions of *other* species' calls.

Fields
------
scientific_name
    GBIF-backbone binomial. Used to join against ``canonical_name`` (XC/iNat)
    and the BirdCODE detection ``Species`` column.
common_name
    English vernacular name (for QA / human readability only).
description
    A short, vivid, onomatopoeic / acoustic description of the vocalization.
    Deliberately free of the species name so the MCQ tests sound, not naming.
vocalization
    One of ``"song"``, ``"call"``, or ``"any"``. Used to gate against the
    Xeno-canto ``behavior`` metadata so a "song" description is not attached
    to a clip the recordist tagged purely as a "call" (and vice versa).

The list intentionally over-provides (~200 species). The build pipeline keeps
only species that actually have Xeno-canto / iNaturalist recordings whose
focal label matches a BirdCODE detection, so a few taxonomy mismatches are
harmless.
"""

from __future__ import annotations

from typing import Literal, TypedDict


class CallDescription(TypedDict):
    scientific_name: str
    common_name: str
    description: str
    vocalization: Literal["song", "call", "any"]


ICONIC_CALL_DESCRIPTIONS: list[CallDescription] = [
    # ── Loons, grebes, waterbirds ─────────────────────────────────────────
    {"scientific_name": "Gavia immer", "common_name": "Common Loon",
     "description": "a long, mournful, tremulous wail that rises and falls like a distant howl",
     "vocalization": "call"},
    {"scientific_name": "Gavia stellata", "common_name": "Red-throated Loon",
     "description": "a rhythmic, goose-like wailing cackle given in flight",
     "vocalization": "call"},
    {"scientific_name": "Podilymbus podiceps", "common_name": "Pied-billed Grebe",
     "description": "a loud, gulping, cuckoo-like series that slows into hollow whoops",
     "vocalization": "call"},
    {"scientific_name": "Botaurus lentiginosus", "common_name": "American Bittern",
     "description": "a deep, pumping, gulping 'oonk-a-loonk' like a stuck water pump",
     "vocalization": "call"},

    # ── Owls ──────────────────────────────────────────────────────────────
    {"scientific_name": "Strix varia", "common_name": "Barred Owl",
     "description": "a rhythmic hooted phrase sounding like 'who cooks for you, who cooks for you all'",
     "vocalization": "call"},
    {"scientific_name": "Bubo virginianus", "common_name": "Great Horned Owl",
     "description": "a series of deep, soft, evenly spaced hoots: 'hoo-hoo-hoo-hoo'",
     "vocalization": "call"},
    {"scientific_name": "Megascops asio", "common_name": "Eastern Screech-Owl",
     "description": "an eerie descending whinny and a long, even trill on one pitch",
     "vocalization": "call"},
    {"scientific_name": "Strix aluco", "common_name": "Tawny Owl",
     "description": "a quavering, breathy 'hoo... huhuhoooo' answered by a sharp 'ke-wick'",
     "vocalization": "call"},
    {"scientific_name": "Athene noctua", "common_name": "Little Owl",
     "description": "a sharp, plaintive, rising 'kiew' repeated at intervals",
     "vocalization": "call"},
    {"scientific_name": "Tyto alba", "common_name": "Barn Owl",
     "description": "a long, harsh, rasping shriek that tears the night air",
     "vocalization": "call"},
    {"scientific_name": "Aegolius acadicus", "common_name": "Northern Saw-whet Owl",
     "description": "a monotonous, mechanical series of evenly spaced 'too' notes like a backing-up truck",
     "vocalization": "call"},
    {"scientific_name": "Ninox novaeseelandiae", "common_name": "Morepork",
     "description": "a soft, double-noted 'more-pork' call repeated through the night",
     "vocalization": "call"},

    # ── Nightjars, potoos, frogmouths ─────────────────────────────────────
    {"scientific_name": "Antrostomus vociferus", "common_name": "Eastern Whip-poor-will",
     "description": "an insistent, rolling three-note chant sounding like 'whip-poor-will' over and over",
     "vocalization": "song"},
    {"scientific_name": "Antrostomus carolinensis", "common_name": "Chuck-will's-widow",
     "description": "a whistled four-syllable phrase like 'chuck-will's-widow' repeated tirelessly",
     "vocalization": "song"},
    {"scientific_name": "Chordeiles minor", "common_name": "Common Nighthawk",
     "description": "a nasal, buzzy 'peent' in flight, followed by a hollow booming whoosh of diving wings",
     "vocalization": "call"},
    {"scientific_name": "Caprimulgus europaeus", "common_name": "European Nightjar",
     "description": "a sustained, mechanical wooden churring that rises and falls in pitch",
     "vocalization": "song"},
    {"scientific_name": "Nyctibius griseus", "common_name": "Common Potoo",
     "description": "a mournful, descending series of pure whistled notes, each lower than the last",
     "vocalization": "song"},
    {"scientific_name": "Podargus strigoides", "common_name": "Tawny Frogmouth",
     "description": "a low, soft, continuous 'oom-oom-oom' grunting hum",
     "vocalization": "call"},

    # ── Cuckoos ───────────────────────────────────────────────────────────
    {"scientific_name": "Cuculus canorus", "common_name": "Common Cuckoo",
     "description": "the familiar two-note 'cuck-oo', the first note higher than the second",
     "vocalization": "song"},
    {"scientific_name": "Coccyzus americanus", "common_name": "Yellow-billed Cuckoo",
     "description": "a hollow, wooden 'kowlp-kowlp-kowlp' that slows and drops in pitch at the end",
     "vocalization": "call"},
    {"scientific_name": "Geococcyx californianus", "common_name": "Greater Roadrunner",
     "description": "a slow, descending series of low, dove-like coos",
     "vocalization": "call"},
    {"scientific_name": "Centropus phasianinus", "common_name": "Pheasant Coucal",
     "description": "a deep, resonant, descending then rising series of hollow 'oop' notes",
     "vocalization": "call"},

    # ── Doves and pigeons ─────────────────────────────────────────────────
    {"scientific_name": "Zenaida macroura", "common_name": "Mourning Dove",
     "description": "a soft, mournful 'coo-OO-oo-oo-oo' with a sorrowful, owl-like quality",
     "vocalization": "song"},
    {"scientific_name": "Streptopelia decaocto", "common_name": "Eurasian Collared-Dove",
     "description": "a repetitive three-note 'coo-COO-cook' with the stress on the middle note",
     "vocalization": "song"},
    {"scientific_name": "Columba palumbus", "common_name": "Common Wood-Pigeon",
     "description": "a soft, husky five-note coo: 'coo-COOO-coo, coo-coo'",
     "vocalization": "song"},
    {"scientific_name": "Streptopelia turtur", "common_name": "European Turtle-Dove",
     "description": "a deep, drowsy, purring 'turrr-turrr' that lulls in the summer heat",
     "vocalization": "song"},
    {"scientific_name": "Patagioenas fasciata", "common_name": "Band-tailed Pigeon",
     "description": "a low, owl-like, hollow 'whoo-whoo' repeated slowly",
     "vocalization": "call"},

    # ── Quail, grouse, gamebirds ──────────────────────────────────────────
    {"scientific_name": "Colinus virginianus", "common_name": "Northern Bobwhite",
     "description": "a clear, rising whistle of two notes sounding like 'bob-WHITE'",
     "vocalization": "song"},
    {"scientific_name": "Callipepla californica", "common_name": "California Quail",
     "description": "an emphatic three-note 'chi-CA-go' with the middle note highest",
     "vocalization": "call"},
    {"scientific_name": "Coturnix coturnix", "common_name": "Common Quail",
     "description": "a liquid, far-carrying three-note 'wet-my-lips' whistle",
     "vocalization": "song"},
    {"scientific_name": "Bonasa umbellus", "common_name": "Ruffed Grouse",
     "description": "an accelerating series of deep, muffled wing-thumps that fade into a blur of drumming",
     "vocalization": "call"},
    {"scientific_name": "Centrocercus urophasianus", "common_name": "Greater Sage-Grouse",
     "description": "bubbling, popping air-sac sounds with swishing and a hollow 'plop'",
     "vocalization": "call"},
    {"scientific_name": "Tympanuchus cupido", "common_name": "Greater Prairie-Chicken",
     "description": "a low, hollow, booming 'whoo-doo-doooh' like blowing across a bottle",
     "vocalization": "call"},
    {"scientific_name": "Meleagris gallopavo", "common_name": "Wild Turkey",
     "description": "a loud, rolling, descending gobble that breaks and bubbles",
     "vocalization": "call"},
    {"scientific_name": "Phasianus colchicus", "common_name": "Ring-necked Pheasant",
     "description": "an explosive, hoarse double-squawk followed by a rapid whir of wingbeats",
     "vocalization": "call"},
    {"scientific_name": "Alectoris rufa", "common_name": "Red-legged Partridge",
     "description": "a rhythmic, steam-engine-like 'chuck-chuck-chukar' chugging",
     "vocalization": "call"},

    # ── Shorebirds, rails, cranes ─────────────────────────────────────────
    {"scientific_name": "Charadrius vociferus", "common_name": "Killdeer",
     "description": "a loud, piercing, repeated 'kill-deer, kill-deer' rising in alarm",
     "vocalization": "call"},
    {"scientific_name": "Vanellus vanellus", "common_name": "Northern Lapwing",
     "description": "a wheezy, electronic 'pee-wit' with whining, squeaky inflections",
     "vocalization": "call"},
    {"scientific_name": "Pluvialis apricaria", "common_name": "European Golden-Plover",
     "description": "a single, plaintive, far-carrying mournful whistle",
     "vocalization": "call"},
    {"scientific_name": "Gallinago gallinago", "common_name": "Common Snipe",
     "description": "a tremulous, bleating winnowing hum produced by vibrating tail feathers in display flight",
     "vocalization": "call"},
    {"scientific_name": "Numenius arquata", "common_name": "Eurasian Curlew",
     "description": "a rising, bubbling cascade of liquid whistles ending in a long mournful 'cur-lee'",
     "vocalization": "song"},
    {"scientific_name": "Tringa totanus", "common_name": "Common Redshank",
     "description": "a ringing, yodeling 'teu-hu-hu' of clear downslurred whistles",
     "vocalization": "call"},
    {"scientific_name": "Haematopus ostralegus", "common_name": "Eurasian Oystercatcher",
     "description": "a shrill, piercing 'kleep-kleep' rising into a fast piping trill",
     "vocalization": "call"},
    {"scientific_name": "Recurvirostra avosetta", "common_name": "Pied Avocet",
     "description": "a soft, fluty, repeated 'kluit' note",
     "vocalization": "call"},
    {"scientific_name": "Grus grus", "common_name": "Common Crane",
     "description": "a loud, rolling, bugling trumpet call carrying for miles",
     "vocalization": "call"},
    {"scientific_name": "Antigone canadensis", "common_name": "Sandhill Crane",
     "description": "a loud, rattling, rolling bugle with a trumpeting, guttural roll",
     "vocalization": "call"},
    {"scientific_name": "Rallus crepitans", "common_name": "Clapper Rail",
     "description": "a dry, accelerating series of harsh 'kek-kek-kek' clattering notes",
     "vocalization": "call"},
    {"scientific_name": "Crex crex", "common_name": "Corn Crake",
     "description": "a monotonous, rasping double 'crex-crex' like a stick drawn across a comb",
     "vocalization": "song"},
    {"scientific_name": "Fulica atra", "common_name": "Eurasian Coot",
     "description": "a sharp, metallic, explosive 'kowk' note",
     "vocalization": "call"},

    # ── Gulls, terns, seabirds ────────────────────────────────────────────
    {"scientific_name": "Larus argentatus", "common_name": "European Herring Gull",
     "description": "a loud, laughing, yelping long-call thrown back with the head",
     "vocalization": "call"},
    {"scientific_name": "Rissa tridactyla", "common_name": "Black-legged Kittiwake",
     "description": "a nasal, repeated 'kitti-waaake' rising and ringing at the colony",
     "vocalization": "call"},
    {"scientific_name": "Sterna hirundo", "common_name": "Common Tern",
     "description": "a grating, downslurred 'kee-arr' with a harsh edge",
     "vocalization": "call"},
    {"scientific_name": "Fratercula arctica", "common_name": "Atlantic Puffin",
     "description": "a low, groaning, chainsaw-like growl from inside the burrow",
     "vocalization": "call"},
    {"scientific_name": "Morus bassanus", "common_name": "Northern Gannet",
     "description": "a harsh, rolling, guttural 'urrah-urrah' chorus at the colony",
     "vocalization": "call"},

    # ── Raptors ───────────────────────────────────────────────────────────
    {"scientific_name": "Haliaeetus leucocephalus", "common_name": "Bald Eagle",
     "description": "a surprisingly weak, high, stuttering whistle-cackle: 'kee-kee-kee-ker'",
     "vocalization": "call"},
    {"scientific_name": "Buteo jamaicensis", "common_name": "Red-tailed Hawk",
     "description": "a harsh, rasping, descending scream: a drawn-out 'kee-eeeee-arr'",
     "vocalization": "call"},
    {"scientific_name": "Falco peregrinus", "common_name": "Peregrine Falcon",
     "description": "a harsh, rapid, scolding 'kak-kak-kak-kak' in alarm",
     "vocalization": "call"},
    {"scientific_name": "Pandion haliaetus", "common_name": "Osprey",
     "description": "a series of short, sharp, plaintive 'cheep' whistles rising in urgency",
     "vocalization": "call"},
    {"scientific_name": "Buteo buteo", "common_name": "Common Buzzard",
     "description": "a far-carrying, plaintive, cat-like mewing 'peee-yow'",
     "vocalization": "call"},
    {"scientific_name": "Milvus milvus", "common_name": "Red Kite",
     "description": "a thin, quavering, whinnying whistle that wavers down the scale",
     "vocalization": "call"},
    {"scientific_name": "Falco tinnunculus", "common_name": "Eurasian Kestrel",
     "description": "a shrill, repeated 'kee-kee-kee' of sharp, excited notes",
     "vocalization": "call"},
    {"scientific_name": "Accipiter nisus", "common_name": "Eurasian Sparrowhawk",
     "description": "a rapid, scolding 'kew-kew-kew-kew' chatter",
     "vocalization": "call"},

    # ── Woodpeckers ───────────────────────────────────────────────────────
    {"scientific_name": "Dryocopus pileatus", "common_name": "Pileated Woodpecker",
     "description": "a loud, ringing, irregular 'kuk-kuk-kuk' that rises and falls, plus deep resonant drumming",
     "vocalization": "call"},
    {"scientific_name": "Colaptes auratus", "common_name": "Northern Flicker",
     "description": "a long, steady, ringing 'wick-wick-wick-wick' on one pitch",
     "vocalization": "call"},
    {"scientific_name": "Melanerpes carolinus", "common_name": "Red-bellied Woodpecker",
     "description": "a rolling, churring 'churr' and a chuckling 'chiv-chiv-chiv'",
     "vocalization": "call"},
    {"scientific_name": "Picus viridis", "common_name": "European Green Woodpecker",
     "description": "a loud, ringing, laughing 'yaffle' that descends slightly",
     "vocalization": "call"},
    {"scientific_name": "Dendrocopos major", "common_name": "Great Spotted Woodpecker",
     "description": "a sharp, explosive single 'kik' and a short, fast burst of drumming",
     "vocalization": "call"},

    # ── Tyrant flycatchers & New World ────────────────────────────────────
    {"scientific_name": "Sayornis phoebe", "common_name": "Eastern Phoebe",
     "description": "a raspy, two-parted 'fee-bee' with a buzzy second note",
     "vocalization": "song"},
    {"scientific_name": "Contopus virens", "common_name": "Eastern Wood-Pewee",
     "description": "a slow, plaintive, slurred whistle: 'pee-a-wee' then a downslurred 'pee-yur'",
     "vocalization": "song"},
    {"scientific_name": "Empidonax minimus", "common_name": "Least Flycatcher",
     "description": "a dry, snappy, repeated 'che-bek, che-bek'",
     "vocalization": "song"},
    {"scientific_name": "Myiarchus crinitus", "common_name": "Great Crested Flycatcher",
     "description": "a loud, rising, whistled 'wheep!' and a rolling 'prrreeet'",
     "vocalization": "call"},
    {"scientific_name": "Tyrannus tyrannus", "common_name": "Eastern Kingbird",
     "description": "a sputtering, electric series of sharp, buzzy 'kit-kit-kitter' notes",
     "vocalization": "call"},
    {"scientific_name": "Pitangus sulphuratus", "common_name": "Great Kiskadee",
     "description": "a loud, exuberant three-note 'kis-ka-dee' shouted from the open",
     "vocalization": "call"},

    # ── Larks, pipits, wagtails ───────────────────────────────────────────
    {"scientific_name": "Alauda arvensis", "common_name": "Eurasian Skylark",
     "description": "an unbroken, tumbling cascade of trills and warbles poured out high overhead",
     "vocalization": "song"},
    {"scientific_name": "Anthus pratensis", "common_name": "Meadow Pipit",
     "description": "a thin, accelerating series of 'tsip' notes ending in a fine descending trill in song-flight",
     "vocalization": "song"},
    {"scientific_name": "Motacilla alba", "common_name": "White Wagtail",
     "description": "a brisk, two-syllable 'chizz-ick' flight call",
     "vocalization": "call"},

    # ── Swallows & swifts ─────────────────────────────────────────────────
    {"scientific_name": "Hirundo rustica", "common_name": "Barn Swallow",
     "description": "a continuous, cheerful, twittering warble ending in a dry rattle",
     "vocalization": "song"},
    {"scientific_name": "Apus apus", "common_name": "Common Swift",
     "description": "a shrill, screaming, high-pitched chorus tearing across the rooftops",
     "vocalization": "call"},

    # ── Wrens ─────────────────────────────────────────────────────────────
    {"scientific_name": "Troglodytes aedon", "common_name": "House Wren",
     "description": "a bubbling, energetic, tumbling cascade of churring trills",
     "vocalization": "song"},
    {"scientific_name": "Troglodytes troglodytes", "common_name": "Eurasian Wren",
     "description": "an astonishingly loud, fast, explosive trill from a tiny bird",
     "vocalization": "song"},
    {"scientific_name": "Thryothorus ludovicianus", "common_name": "Carolina Wren",
     "description": "a loud, rolling, repeated 'teakettle-teakettle-teakettle'",
     "vocalization": "song"},
    {"scientific_name": "Campylorhynchus brunneicapillus", "common_name": "Cactus Wren",
     "description": "a low, harsh, accelerating 'chug-chug-chug' like a car failing to start",
     "vocalization": "song"},

    # ── Thrushes, robins, chats ───────────────────────────────────────────
    {"scientific_name": "Turdus migratorius", "common_name": "American Robin",
     "description": "a clear, caroling series of rising and falling whistled phrases: 'cheerily, cheer-up, cheerio'",
     "vocalization": "song"},
    {"scientific_name": "Turdus merula", "common_name": "Common Blackbird",
     "description": "a rich, mellow, fluty warble of leisurely, melodious phrases",
     "vocalization": "song"},
    {"scientific_name": "Turdus philomelos", "common_name": "Song Thrush",
     "description": "loud, ringing musical phrases, each distinct phrase repeated two or three times",
     "vocalization": "song"},
    {"scientific_name": "Hylocichla mustelina", "common_name": "Wood Thrush",
     "description": "a flute-like, ethereal phrase ending in a liquid 'ee-oh-lay' and a fine trill",
     "vocalization": "song"},
    {"scientific_name": "Catharus guttatus", "common_name": "Hermit Thrush",
     "description": "a serene, flute-like phrase beginning on a long clear note, then spiraling ethereal cascades",
     "vocalization": "song"},
    {"scientific_name": "Catharus fuscescens", "common_name": "Veery",
     "description": "a downward-spiraling, breezy, reverberating cascade of 'veer-veer-veer' notes",
     "vocalization": "song"},
    {"scientific_name": "Luscinia megarhynchos", "common_name": "Common Nightingale",
     "description": "a powerful, varied torrent of rich whistles, deep throbbing notes, and crescendos, often at night",
     "vocalization": "song"},
    {"scientific_name": "Erithacus rubecula", "common_name": "European Robin",
     "description": "a wistful, silvery, trickling warble of high, thin musical phrases",
     "vocalization": "song"},
    {"scientific_name": "Sialia sialis", "common_name": "Eastern Bluebird",
     "description": "a soft, mellow, warbling 'chur-lee, chur-lee' with a musical, contented tone",
     "vocalization": "song"},

    # ── Mimids ────────────────────────────────────────────────────────────
    {"scientific_name": "Mimus polyglottos", "common_name": "Northern Mockingbird",
     "description": "an endless medley of mimicked phrases, each repeated several times before switching",
     "vocalization": "song"},
    {"scientific_name": "Dumetella carolinensis", "common_name": "Gray Catbird",
     "description": "a rambling jumble of squeaky notes punctuated by a distinctive cat-like 'mew'",
     "vocalization": "song"},
    {"scientific_name": "Toxostoma rufum", "common_name": "Brown Thrasher",
     "description": "a long string of varied musical phrases, each typically repeated exactly twice",
     "vocalization": "song"},

    # ── Old World warblers, kinglets, gnatcatchers ────────────────────────
    {"scientific_name": "Sylvia atricapilla", "common_name": "Eurasian Blackcap",
     "description": "a rich, fluty warble that gathers into a clear, loud, ringing final flourish",
     "vocalization": "song"},
    {"scientific_name": "Phylloscopus collybita", "common_name": "Common Chiffchaff",
     "description": "a monotonous, repetitive 'chiff-chaff-chiff-chaff' jumping between two pitches",
     "vocalization": "song"},
    {"scientific_name": "Phylloscopus trochilus", "common_name": "Willow Warbler",
     "description": "a gentle, descending, wistful cascade of liquid notes that fades away softly",
     "vocalization": "song"},
    {"scientific_name": "Acrocephalus scirpaceus", "common_name": "Eurasian Reed Warbler",
     "description": "a steady, churring, conversational chatter of repeated grating phrases from the reeds",
     "vocalization": "song"},
    {"scientific_name": "Locustella naevia", "common_name": "Common Grasshopper Warbler",
     "description": "a sustained, mechanical, insect-like reeling trill on one pitch",
     "vocalization": "song"},
    {"scientific_name": "Regulus regulus", "common_name": "Goldcrest",
     "description": "an extremely thin, high, rhythmic 'cedar-cedar-cedar' ending in a flourish",
     "vocalization": "song"},

    # ── Chickadees, tits, nuthatches ──────────────────────────────────────
    {"scientific_name": "Poecile atricapillus", "common_name": "Black-capped Chickadee",
     "description": "a buzzy, scolding 'chick-a-dee-dee-dee' and a clear two-note whistled 'fee-bee'",
     "vocalization": "call"},
    {"scientific_name": "Cyanistes caeruleus", "common_name": "Eurasian Blue Tit",
     "description": "a high 'tsee-tsee' followed by a fast, silvery, descending trill",
     "vocalization": "song"},
    {"scientific_name": "Parus major", "common_name": "Great Tit",
     "description": "a ringing, repeated, two-note 'teacher-teacher-teacher' like a squeaky see-saw",
     "vocalization": "song"},
    {"scientific_name": "Sitta carolinensis", "common_name": "White-breasted Nuthatch",
     "description": "a nasal, repeated, low 'yank-yank-yank' with a tin-trumpet quality",
     "vocalization": "call"},
    {"scientific_name": "Sitta europaea", "common_name": "Eurasian Nuthatch",
     "description": "a loud, liquid, ringing 'pew-pew-pew' of clear whistled notes",
     "vocalization": "call"},

    # ── Corvids ───────────────────────────────────────────────────────────
    {"scientific_name": "Cyanocitta cristata", "common_name": "Blue Jay",
     "description": "a loud, harsh, descending 'jay-jay' scream and a musical, bell-like 'queedle'",
     "vocalization": "call"},
    {"scientific_name": "Corvus corax", "common_name": "Common Raven",
     "description": "a deep, resonant, croaking 'gronk-gronk' far lower than any crow",
     "vocalization": "call"},
    {"scientific_name": "Corvus brachyrhynchos", "common_name": "American Crow",
     "description": "a familiar, harsh, repeated 'caw-caw-caw'",
     "vocalization": "call"},
    {"scientific_name": "Pica pica", "common_name": "Eurasian Magpie",
     "description": "a harsh, machine-gun-like, chattering rattle: 'chacka-chacka-chacka'",
     "vocalization": "call"},
    {"scientific_name": "Garrulus glandarius", "common_name": "Eurasian Jay",
     "description": "a harsh, tearing, screeching 'kraaah' like ripping cloth",
     "vocalization": "call"},
    {"scientific_name": "Nucifraga columbiana", "common_name": "Clark's Nutcracker",
     "description": "a long, grating, drawn-out 'kraaa' croak",
     "vocalization": "call"},

    # ── Buntings, finches, sparrows ───────────────────────────────────────
    {"scientific_name": "Spizella passerina", "common_name": "Chipping Sparrow",
     "description": "a long, dry, mechanical trill of evenly spaced chips on one pitch",
     "vocalization": "song"},
    {"scientific_name": "Melospiza melodia", "common_name": "Song Sparrow",
     "description": "three clear introductory notes followed by a varied, buzzy, trilling jumble",
     "vocalization": "song"},
    {"scientific_name": "Zonotrichia leucophrys", "common_name": "White-crowned Sparrow",
     "description": "a clear whistle followed by buzzy trills and a plaintive falling phrase",
     "vocalization": "song"},
    {"scientific_name": "Zonotrichia albicollis", "common_name": "White-throated Sparrow",
     "description": "a clear, wavering whistle sounding like 'oh-sweet-canada-canada-canada'",
     "vocalization": "song"},
    {"scientific_name": "Passerella iliaca", "common_name": "Fox Sparrow",
     "description": "a rich, ringing series of sweet, slurred whistles and buzzes",
     "vocalization": "song"},
    {"scientific_name": "Pipilo erythrophthalmus", "common_name": "Eastern Towhee",
     "description": "a bright phrase sounding like 'drink-your-TEA' ending in a musical trill",
     "vocalization": "song"},
    {"scientific_name": "Junco hyemalis", "common_name": "Dark-eyed Junco",
     "description": "a simple, even, musical trill on one pitch, like a ringing little bell",
     "vocalization": "song"},
    {"scientific_name": "Emberiza citrinella", "common_name": "Yellowhammer",
     "description": "a rhythmic phrase of repeated notes ending in a long high one: 'a-little-bit-of-bread-and-no-cheese'",
     "vocalization": "song"},
    {"scientific_name": "Emberiza calandra", "common_name": "Corn Bunting",
     "description": "a dry, accelerating, jangling phrase like shaking a bunch of keys",
     "vocalization": "song"},
    {"scientific_name": "Fringilla coelebs", "common_name": "Common Chaffinch",
     "description": "a cheerful, accelerating descending rattle that ends in a flourishing terminal twiddle",
     "vocalization": "song"},
    {"scientific_name": "Carduelis carduelis", "common_name": "European Goldfinch",
     "description": "a liquid, tinkling, twittering 'tickle-it' interspersed with trills",
     "vocalization": "song"},
    {"scientific_name": "Chloris chloris", "common_name": "European Greenfinch",
     "description": "a series of trills and twitters punctuated by a drawn-out, wheezy, nasal 'dzweee'",
     "vocalization": "song"},
    {"scientific_name": "Pyrrhula pyrrhula", "common_name": "Eurasian Bullfinch",
     "description": "a soft, low, mournful, piping single whistle",
     "vocalization": "call"},
    {"scientific_name": "Loxia curvirostra", "common_name": "Red Crossbill",
     "description": "a hard, emphatic, repeated 'jip-jip-jip' flight call",
     "vocalization": "call"},
    {"scientific_name": "Spinus tristis", "common_name": "American Goldfinch",
     "description": "a lilting flight call sounding like 'po-ta-to-chip' delivered in bounding flight",
     "vocalization": "call"},
    {"scientific_name": "Haemorhous mexicanus", "common_name": "House Finch",
     "description": "a long, bright, warbling jumble ending in a buzzy, upslurred 'zreee'",
     "vocalization": "song"},
    {"scientific_name": "Coccothraustes coccothraustes", "common_name": "Hawfinch",
     "description": "an abrupt, hard, explosive 'tzik' click",
     "vocalization": "call"},

    # ── New World warblers & icterids ─────────────────────────────────────
    {"scientific_name": "Setophaga petechia", "common_name": "Yellow Warbler",
     "description": "a bright, sweet phrase sounding like 'sweet-sweet-sweet-I'm-so-sweet'",
     "vocalization": "song"},
    {"scientific_name": "Geothlypis trichas", "common_name": "Common Yellowthroat",
     "description": "a rolling, repeated 'witchety-witchety-witchety'",
     "vocalization": "song"},
    {"scientific_name": "Setophaga ruticilla", "common_name": "American Redstart",
     "description": "a series of high, thin notes ending with an emphatic downslurred accent",
     "vocalization": "song"},
    {"scientific_name": "Mniotilta varia", "common_name": "Black-and-white Warbler",
     "description": "a thin, high, squeaky 'wee-see-wee-see' like a turning, ungreased wheel",
     "vocalization": "song"},
    {"scientific_name": "Seiurus aurocapilla", "common_name": "Ovenbird",
     "description": "an emphatic, accelerating, crescendoing chant: 'teacher-TEACHER-TEACHER'",
     "vocalization": "song"},
    {"scientific_name": "Icteria virens", "common_name": "Yellow-breasted Chat",
     "description": "a bizarre, disjointed medley of whistles, harsh chuckles, mews, and rattles with long pauses",
     "vocalization": "song"},
    {"scientific_name": "Sturnella neglecta", "common_name": "Western Meadowlark",
     "description": "a rich, flute-like, gurgling series of bubbling, descending whistled phrases",
     "vocalization": "song"},
    {"scientific_name": "Dolichonyx oryzivorus", "common_name": "Bobolink",
     "description": "a bubbling, tumbling, banjo-like jangle of metallic, rollicking notes in flight",
     "vocalization": "song"},
    {"scientific_name": "Agelaius phoeniceus", "common_name": "Red-winged Blackbird",
     "description": "a gurgling, liquid 'conk-la-reee' ending in a buzzy, trilled flourish",
     "vocalization": "song"},
    {"scientific_name": "Quiscalus quiscula", "common_name": "Common Grackle",
     "description": "a harsh, squeaky, rising 'readle-eak' like a rusty gate swinging open",
     "vocalization": "song"},
    {"scientific_name": "Molothrus ater", "common_name": "Brown-headed Cowbird",
     "description": "a liquid, gurgling, bubbling 'glug-glug-glee' ending in a high, thin whistle",
     "vocalization": "song"},
    {"scientific_name": "Icterus galbula", "common_name": "Baltimore Oriole",
     "description": "a rich, clear, flute-like series of whistled notes, full and mellow",
     "vocalization": "song"},

    # ── Cardinals, tanagers, grosbeaks ────────────────────────────────────
    {"scientific_name": "Cardinalis cardinalis", "common_name": "Northern Cardinal",
     "description": "loud, clear, sliding whistles like 'cheer-cheer-cheer' and 'birdy-birdy-birdy'",
     "vocalization": "song"},
    {"scientific_name": "Piranga olivacea", "common_name": "Scarlet Tanager",
     "description": "a hoarse, burry, robin-like caroling with a sore-throat rasp, and a sharp 'chick-burr' call",
     "vocalization": "song"},
    {"scientific_name": "Pheucticus ludovicianus", "common_name": "Rose-breasted Grosbeak",
     "description": "a sweet, rich, robin-like warble, smoother and more operatic, with a squeaky 'eek' call",
     "vocalization": "song"},
    {"scientific_name": "Passerina cyanea", "common_name": "Indigo Bunting",
     "description": "a bright, paired-phrase song: 'sweet-sweet, where-where, here-here'",
     "vocalization": "song"},
    {"scientific_name": "Spiza americana", "common_name": "Dickcissel",
     "description": "a buzzy, mechanical phrase sounding like its name: 'dick-dick-cissel'",
     "vocalization": "song"},

    # ── Vireos ────────────────────────────────────────────────────────────
    {"scientific_name": "Vireo olivaceus", "common_name": "Red-eyed Vireo",
     "description": "an endless series of short, robin-like phrases with a rising-falling, questioning cadence",
     "vocalization": "song"},
    {"scientific_name": "Vireo griseus", "common_name": "White-eyed Vireo",
     "description": "an explosive, sharp phrase often beginning and ending with a sharp 'chick'",
     "vocalization": "song"},

    # ── Starlings, shrikes, waxwings ──────────────────────────────────────
    {"scientific_name": "Sturnus vulgaris", "common_name": "European Starling",
     "description": "a rambling medley of clicks, whistles, rattles, and mimicked sounds with a rising whistle",
     "vocalization": "song"},
    {"scientific_name": "Bombycilla cedrorum", "common_name": "Cedar Waxwing",
     "description": "a very high, thin, hissing, lisping 'seee' whistle",
     "vocalization": "call"},
    {"scientific_name": "Lanius collurio", "common_name": "Red-backed Shrike",
     "description": "a harsh, chattering warble mixed with grating notes and snatches of mimicry",
     "vocalization": "song"},

    # ── Hummingbirds, kingfishers, bee-eaters ─────────────────────────────
    {"scientific_name": "Archilochus colubris", "common_name": "Ruby-throated Hummingbird",
     "description": "a rapid series of high, squeaky, mousy 'chip' notes",
     "vocalization": "call"},
    {"scientific_name": "Megaceryle alcyon", "common_name": "Belted Kingfisher",
     "description": "a loud, harsh, dry, mechanical rattle delivered in flight",
     "vocalization": "call"},
    {"scientific_name": "Alcedo atthis", "common_name": "Common Kingfisher",
     "description": "a shrill, piercing, high 'tseee' whistle as it streaks low over the water",
     "vocalization": "call"},
    {"scientific_name": "Merops apiaster", "common_name": "European Bee-eater",
     "description": "a soft, liquid, rolling, far-carrying 'prrroot' given in flight",
     "vocalization": "call"},
    {"scientific_name": "Upupa epops", "common_name": "Eurasian Hoopoe",
     "description": "a soft, far-carrying, hollow trisyllabic 'oop-oop-oop'",
     "vocalization": "song"},

    # ── Iconic non-passerines elsewhere ───────────────────────────────────
    {"scientific_name": "Dacelo novaeguineae", "common_name": "Laughing Kookaburra",
     "description": "a raucous, escalating chorus of maniacal, cackling, human-like laughter",
     "vocalization": "call"},
    {"scientific_name": "Menura novaehollandiae", "common_name": "Superb Lyrebird",
     "description": "an astonishing, loud medley faithfully mimicking other species and mechanical sounds",
     "vocalization": "song"},
    {"scientific_name": "Gymnorhina tibicen", "common_name": "Australian Magpie",
     "description": "a rich, complex, organ-like carolling of fluty, warbling, melodic phrases",
     "vocalization": "song"},
    {"scientific_name": "Manorina melanocephala", "common_name": "Noisy Miner",
     "description": "a loud, insistent, repeated 'pwee-pwee-pwee' alarm chorus",
     "vocalization": "call"},
    {"scientific_name": "Eolophus roseicapilla", "common_name": "Galah",
     "description": "a harsh, grating, metallic, screeching 'chee-chee' in flight",
     "vocalization": "call"},
    {"scientific_name": "Cacatua galerita", "common_name": "Sulphur-crested Cockatoo",
     "description": "an extremely loud, harsh, raucous, screeching 'aaaargh'",
     "vocalization": "call"},
    {"scientific_name": "Strepera graculina", "common_name": "Pied Currawong",
     "description": "a loud, ringing, far-carrying 'curra-wong' with a wild, wailing quality",
     "vocalization": "call"},
    {"scientific_name": "Grallina cyanoleuca", "common_name": "Magpie-lark",
     "description": "a loud, repeated, antiphonal 'tee-tee' duet between paired birds",
     "vocalization": "call"},
    {"scientific_name": "Phylidonyris novaehollandiae", "common_name": "New Holland Honeyeater",
     "description": "a busy, scratchy, metallic chattering of sharp, energetic notes",
     "vocalization": "call"},
    {"scientific_name": "Anthochaera carunculata", "common_name": "Red Wattlebird",
     "description": "a harsh, coughing, hacking series ending in a guttural 'yak-a-yak'",
     "vocalization": "call"},

    # ── More Holarctic favorites ──────────────────────────────────────────
    {"scientific_name": "Cuculus solitarius", "common_name": "Red-chested Cuckoo",
     "description": "an insistent, ringing three-note whistle: 'piet-my-vrou' rising then falling",
     "vocalization": "song"},
    {"scientific_name": "Clamator glandarius", "common_name": "Great Spotted Cuckoo",
     "description": "a loud, harsh, rattling, crow-like 'kee-ow-kee-ow' chatter",
     "vocalization": "call"},
    {"scientific_name": "Jynx torquilla", "common_name": "Eurasian Wryneck",
     "description": "a nasal, falcon-like series of repeated 'quee-quee-quee' notes",
     "vocalization": "song"},
    {"scientific_name": "Oriolus oriolus", "common_name": "Eurasian Golden Oriole",
     "description": "a beautiful, fluty, exotic, far-carrying 'weela-wee-oo' whistle",
     "vocalization": "song"},
    {"scientific_name": "Cinclus cinclus", "common_name": "White-throated Dipper",
     "description": "a rich, rippling warble of grating and sweet notes given over rushing water",
     "vocalization": "song"},
    {"scientific_name": "Saxicola rubicola", "common_name": "European Stonechat",
     "description": "a hard, scolding 'tac-tac' like two stones being knocked together",
     "vocalization": "call"},
    {"scientific_name": "Oenanthe oenanthe", "common_name": "Northern Wheatear",
     "description": "a hard, grating 'chack-chack' mixed with a short scratchy warble",
     "vocalization": "call"},
    {"scientific_name": "Prunella modularis", "common_name": "Dunnock",
     "description": "a thin, hurried, even, slightly flat warble with no clear pattern",
     "vocalization": "song"},
    {"scientific_name": "Troglodytes pacificus", "common_name": "Pacific Wren",
     "description": "an incredibly long, rapid, tinkling cascade of high trills and buzzes",
     "vocalization": "song"},
    {"scientific_name": "Certhia familiaris", "common_name": "Eurasian Treecreeper",
     "description": "a thin, high, descending phrase ending in a flourish, easily missed",
     "vocalization": "song"},

    # ── Cisticolas, weavers, African favorites ────────────────────────────
    {"scientific_name": "Pycnonotus barbatus", "common_name": "Common Bulbul",
     "description": "a cheerful, liquid, chattering phrase often rendered 'quick-doctor-quick'",
     "vocalization": "song"},
    {"scientific_name": "Laniarius major", "common_name": "Tropical Boubou",
     "description": "a perfectly synchronized bell-like duet of liquid whistles and harsh snarls",
     "vocalization": "song"},
    {"scientific_name": "Numida meleagris", "common_name": "Helmeted Guineafowl",
     "description": "a loud, grating, repetitive, metallic 'kek-kek-kaaa' clatter",
     "vocalization": "call"},
    {"scientific_name": "Corythaixoides concolor", "common_name": "Gray Go-away-bird",
     "description": "a loud, drawn-out, nasal, descending 'g'way' like a child whining",
     "vocalization": "call"},

    # ── Frogs & a few mammals (well-described, often on iNat) ─────────────
    {"scientific_name": "Pseudacris crucifer", "common_name": "Spring Peeper",
     "description": "a high, clear, single peeping whistle repeated about once a second, massed into a sleigh-bell chorus",
     "vocalization": "call"},
    {"scientific_name": "Hyla cinerea", "common_name": "American Green Treefrog",
     "description": "a nasal, honking, repeated 'quonk' like a distant duck or cowbell",
     "vocalization": "call"},
    {"scientific_name": "Lithobates catesbeianus", "common_name": "American Bullfrog",
     "description": "a deep, resonant, low-pitched 'jug-o-rum' bellow",
     "vocalization": "call"},
    {"scientific_name": "Anaxyrus americanus", "common_name": "American Toad",
     "description": "a long, sustained, high, musical trill held for many seconds",
     "vocalization": "call"},
    {"scientific_name": "Dryophytes versicolor", "common_name": "Gray Treefrog",
     "description": "a short, flutey, melodic, birdlike trill repeated at intervals",
     "vocalization": "call"},

    # ── Additional iconic, well-described voices ──────────────────────────
    {"scientific_name": "Acrocephalus arundinaceus", "common_name": "Great Reed Warbler",
     "description": "a loud, harsh, grating song of croaking 'karra-karra-kreet-kreet' phrases from the reeds",
     "vocalization": "song"},
    {"scientific_name": "Luscinia svecica", "common_name": "Bluethroat",
     "description": "a rich, accelerating song built from a clear ringing 'ting-ting-ting' that gathers speed",
     "vocalization": "song"},
    {"scientific_name": "Phoenicurus phoenicurus", "common_name": "Common Redstart",
     "description": "a short, melancholy warble that begins sweetly then dissolves into a feeble, scratchy jumble",
     "vocalization": "song"},
    {"scientific_name": "Saxicola rubetra", "common_name": "Whinchat",
     "description": "a short, scratchy warble interspersed with a hard, ticking 'tic-tic'",
     "vocalization": "song"},
    {"scientific_name": "Anthus trivialis", "common_name": "Tree Pipit",
     "description": "a rich, accelerating trill delivered in parachuting song-flight, ending in a slow drawn-out 'see-er'",
     "vocalization": "song"},
    {"scientific_name": "Carpodacus erythrinus", "common_name": "Common Rosefinch",
     "description": "a clear, lilting, whistled phrase rendered 'pleased-to-meet-you'",
     "vocalization": "song"},
    {"scientific_name": "Emberiza schoeniclus", "common_name": "Reed Bunting",
     "description": "a short, halting, disjointed phrase of squeaky notes: 'tweek-tweek-tweek-tississick'",
     "vocalization": "song"},
    {"scientific_name": "Tetrao urogallus", "common_name": "Western Capercaillie",
     "description": "a strange display of accelerating clicks ending in a pop like a cork, then a wheezy gurgle",
     "vocalization": "call"},
    {"scientific_name": "Lagopus lagopus", "common_name": "Willow Ptarmigan",
     "description": "a loud, staccato, laughing 'go-back, go-back, go-back' cackle",
     "vocalization": "call"},
    {"scientific_name": "Pluvialis squatarola", "common_name": "Black-bellied Plover",
     "description": "a plaintive, three-note, slurred whistle: 'pee-oo-ee' falling then rising",
     "vocalization": "call"},
    {"scientific_name": "Tringa nebularia", "common_name": "Common Greenshank",
     "description": "a ringing, even, three-note 'tew-tew-tew' on one pitch",
     "vocalization": "call"},
    {"scientific_name": "Actitis macularius", "common_name": "Spotted Sandpiper",
     "description": "a clear, whistled 'peet-weet-weet-weet' that drops in pitch",
     "vocalization": "call"},
    {"scientific_name": "Sterna paradisaea", "common_name": "Arctic Tern",
     "description": "a high, grating, drawn-out 'kee-arrr' with a piercing whistled 'kee-kee'",
     "vocalization": "call"},
    {"scientific_name": "Asio otus", "common_name": "Long-eared Owl",
     "description": "a soft, low, evenly spaced, moaning 'ooh' hoot repeated at long intervals",
     "vocalization": "call"},
    {"scientific_name": "Glaucidium passerinum", "common_name": "Eurasian Pygmy-Owl",
     "description": "a monotonous series of soft, slightly rising, fluty single 'pew' whistles",
     "vocalization": "call"},
    {"scientific_name": "Picus canus", "common_name": "Gray-headed Woodpecker",
     "description": "a clear, fluty series of whistles that slows and falls in pitch and volume toward the end",
     "vocalization": "call"},
    {"scientific_name": "Lullula arborea", "common_name": "Woodlark",
     "description": "a beautiful, melancholy, descending series of fluty 'lu-lu-lu' phrases, often at night",
     "vocalization": "song"},
    {"scientific_name": "Carduelis cannabina", "common_name": "Common Linnet",
     "description": "a pleasant, fast, twittering warble of varied musical and nasal notes",
     "vocalization": "song"},
    {"scientific_name": "Tachycineta bicolor", "common_name": "Tree Swallow",
     "description": "a liquid, cheerful, gurgling twitter of sweet, chirping notes",
     "vocalization": "song"},
    {"scientific_name": "Vanellus miles", "common_name": "Masked Lapwing",
     "description": "a loud, harsh, staccato, rattling 'kekekekek' alarm",
     "vocalization": "call"},
    {"scientific_name": "Todiramphus sanctus", "common_name": "Sacred Kingfisher",
     "description": "a loud, monotonous, repeated 'kek-kek-kek-kek' on one pitch",
     "vocalization": "call"},

    # ══ Expansion batch: 100 more iconic, well-described voices ═══════════
    # ── Owls ──────────────────────────────────────────────────────────────
    {"scientific_name": "Bubo bubo", "common_name": "Eurasian Eagle-Owl",
     "description": "a deep, far-carrying, booming 'ooh-hu' with the stress on the first syllable",
     "vocalization": "call"},
    {"scientific_name": "Otus scops", "common_name": "Eurasian Scops-Owl",
     "description": "a monotonous, evenly spaced, whistled 'tyuu' repeated every few seconds",
     "vocalization": "call"},
    {"scientific_name": "Strix nebulosa", "common_name": "Great Gray Owl",
     "description": "a series of very deep, soft, evenly spaced booming hoots descending slightly",
     "vocalization": "call"},
    {"scientific_name": "Aegolius funereus", "common_name": "Boreal Owl",
     "description": "a rapid, bouncing series of soft 'po-po-po-po' notes rising in volume",
     "vocalization": "call"},
    {"scientific_name": "Megascops kennicottii", "common_name": "Western Screech-Owl",
     "description": "an accelerating series of soft hoots like a bouncing ball coming to rest",
     "vocalization": "call"},

    # ── Doves & cuckoos ───────────────────────────────────────────────────
    {"scientific_name": "Spilopelia chinensis", "common_name": "Spotted Dove",
     "description": "a gentle, rolling 'coo-croo-croo' with a low, purring quality",
     "vocalization": "song"},
    {"scientific_name": "Streptopelia senegalensis", "common_name": "Laughing Dove",
     "description": "a soft, bubbling, laughing 'coo-COO-coo-coo-coo'",
     "vocalization": "song"},
    {"scientific_name": "Eudynamys scolopaceus", "common_name": "Asian Koel",
     "description": "a loud, rising, repeated 'ko-EL, ko-EL' growing more frantic and higher each time",
     "vocalization": "call"},
    {"scientific_name": "Centropus sinensis", "common_name": "Greater Coucal",
     "description": "a deep, resonant, descending series of hollow 'coop-coop-coop' notes",
     "vocalization": "call"},
    {"scientific_name": "Cacomantis flabelliformis", "common_name": "Fan-tailed Cuckoo",
     "description": "a melancholy, descending, trilled whistle that fades away",
     "vocalization": "call"},
    {"scientific_name": "Crotophaga ani", "common_name": "Smooth-billed Ani",
     "description": "a whining, rising, slurred 'ah-neee' with a metallic edge",
     "vocalization": "call"},

    # ── Gamebirds & peafowl ───────────────────────────────────────────────
    {"scientific_name": "Pavo cristatus", "common_name": "Indian Peafowl",
     "description": "a loud, far-carrying, wailing 'may-awe' like a plaintive scream",
     "vocalization": "call"},
    {"scientific_name": "Lyrurus tetrix", "common_name": "Black Grouse",
     "description": "a continuous, bubbling, dove-like rookooing churr from the communal lek",
     "vocalization": "call"},

    # ── Waterfowl, grebes, rails ──────────────────────────────────────────
    {"scientific_name": "Branta canadensis", "common_name": "Canada Goose",
     "description": "a loud, resonant, two-syllable honking 'ah-HONK'",
     "vocalization": "call"},
    {"scientific_name": "Anas platyrhynchos", "common_name": "Mallard",
     "description": "a series of loud, descending, nasal quacks",
     "vocalization": "call"},
    {"scientific_name": "Aix sponsa", "common_name": "Wood Duck",
     "description": "a rising, squealing 'oo-EEK' given as it flushes",
     "vocalization": "call"},
    {"scientific_name": "Cygnus cygnus", "common_name": "Whooper Swan",
     "description": "a loud, bugling, trumpeting 'whoop-whoop' carrying across the water",
     "vocalization": "call"},
    {"scientific_name": "Tachybaptus ruficollis", "common_name": "Little Grebe",
     "description": "a high, whinnying, rippling trill that falls away at the end",
     "vocalization": "call"},
    {"scientific_name": "Podiceps cristatus", "common_name": "Great Crested Grebe",
     "description": "a far-carrying, grating, barking 'gruk-gruk'",
     "vocalization": "call"},
    {"scientific_name": "Gallinula chloropus", "common_name": "Common Moorhen",
     "description": "an explosive, bubbling, liquid 'kurr-uk'",
     "vocalization": "call"},
    {"scientific_name": "Rallus aquaticus", "common_name": "Water Rail",
     "description": "a sudden burst of pig-like grunting and squealing from dense reeds",
     "vocalization": "call"},

    # ── Shorebirds ────────────────────────────────────────────────────────
    {"scientific_name": "Scolopax minor", "common_name": "American Woodcock",
     "description": "a buzzy, nasal 'peent' on the ground followed by high twittering wings in display flight",
     "vocalization": "call"},
    {"scientific_name": "Scolopax rusticola", "common_name": "Eurasian Woodcock",
     "description": "a low, frog-like grunting alternating with a sharp, sneezing 'tsiwick' in roding flight",
     "vocalization": "call"},
    {"scientific_name": "Numenius phaeopus", "common_name": "Whimbrel",
     "description": "a rapid, even series of about seven short, rippling whistles on one pitch",
     "vocalization": "call"},
    {"scientific_name": "Tringa melanoleuca", "common_name": "Greater Yellowlegs",
     "description": "a loud, ringing, three-note 'tew-tew-tew' whistle",
     "vocalization": "call"},
    {"scientific_name": "Burhinus oedicnemus", "common_name": "Eurasian Thick-knee",
     "description": "an eerie, wailing 'cur-lee' rising then falling, given at night",
     "vocalization": "call"},
    {"scientific_name": "Himantopus himantopus", "common_name": "Black-winged Stilt",
     "description": "a sharp, yapping, repeated 'kik-kik-kik' like a small excited dog",
     "vocalization": "call"},
    {"scientific_name": "Arenaria interpres", "common_name": "Ruddy Turnstone",
     "description": "a low, hard, staccato, rattling chatter",
     "vocalization": "call"},

    # ── Gulls & seabirds ──────────────────────────────────────────────────
    {"scientific_name": "Chroicocephalus ridibundus", "common_name": "Black-headed Gull",
     "description": "a harsh, grating, laughing 'kee-arr'",
     "vocalization": "call"},
    {"scientific_name": "Larus marinus", "common_name": "Great Black-backed Gull",
     "description": "a deep, guttural, gruff 'owk-owk' lower than other gulls",
     "vocalization": "call"},

    # ── Raptors ───────────────────────────────────────────────────────────
    {"scientific_name": "Accipiter gentilis", "common_name": "Northern Goshawk",
     "description": "a fast, ringing, scolding 'gek-gek-gek-gek'",
     "vocalization": "call"},
    {"scientific_name": "Falco sparverius", "common_name": "American Kestrel",
     "description": "a rapid, shrill, excited 'klee-klee-klee'",
     "vocalization": "call"},
    {"scientific_name": "Buteo lineatus", "common_name": "Red-shouldered Hawk",
     "description": "a loud, repeated, downslurred 'kee-yar, kee-yar'",
     "vocalization": "call"},

    # ── Woodpeckers ───────────────────────────────────────────────────────
    {"scientific_name": "Dryobates pubescens", "common_name": "Downy Woodpecker",
     "description": "a sharp 'pik' and a descending, whinnying rattle that drops in pitch",
     "vocalization": "call"},
    {"scientific_name": "Dryobates villosus", "common_name": "Hairy Woodpecker",
     "description": "a sharp, emphatic 'peek' and a hard, even rattle on one pitch",
     "vocalization": "call"},
    {"scientific_name": "Sphyrapicus varius", "common_name": "Yellow-bellied Sapsucker",
     "description": "a nasal, slurred, cat-like mewing and an irregular, stuttering drum",
     "vocalization": "call"},
    {"scientific_name": "Melanerpes erythrocephalus", "common_name": "Red-headed Woodpecker",
     "description": "a loud, harsh, churring 'queeah'",
     "vocalization": "call"},

    # ── Tyrant flycatchers ────────────────────────────────────────────────
    {"scientific_name": "Tyrannus verticalis", "common_name": "Western Kingbird",
     "description": "a sharp, bickering series of sputtering 'kit-kit-keet' notes",
     "vocalization": "call"},
    {"scientific_name": "Contopus sordidulus", "common_name": "Western Wood-Pewee",
     "description": "a harsh, burry, descending 'pheeeer'",
     "vocalization": "song"},
    {"scientific_name": "Empidonax traillii", "common_name": "Willow Flycatcher",
     "description": "a sneezy, burry, two-parted 'fitz-bew'",
     "vocalization": "song"},
    {"scientific_name": "Sayornis nigricans", "common_name": "Black Phoebe",
     "description": "a thin, buzzy, rising-then-falling 'fee-bee, fee-bew'",
     "vocalization": "song"},
    {"scientific_name": "Sayornis saya", "common_name": "Say's Phoebe",
     "description": "a plaintive, downslurred, melancholy 'pee-ur'",
     "vocalization": "song"},

    # ── Larks & swallows ──────────────────────────────────────────────────
    {"scientific_name": "Galerida cristata", "common_name": "Crested Lark",
     "description": "a melancholy, liquid, fluty 'whee-whee-wheeoo'",
     "vocalization": "song"},
    {"scientific_name": "Eremophila alpestris", "common_name": "Horned Lark",
     "description": "a high, tinkling, glassy series of soft, jumbled notes",
     "vocalization": "song"},
    {"scientific_name": "Progne subis", "common_name": "Purple Martin",
     "description": "a rich, liquid, gurgling, throaty warble ending in low chuckles",
     "vocalization": "song"},

    # ── Wrens ─────────────────────────────────────────────────────────────
    {"scientific_name": "Catherpes mexicanus", "common_name": "Canyon Wren",
     "description": "a beautiful, cascading series of clear whistles tumbling down the scale",
     "vocalization": "song"},
    {"scientific_name": "Cistothorus palustris", "common_name": "Marsh Wren",
     "description": "a reedy, gurgling, mechanical rattle from the cattails",
     "vocalization": "song"},
    {"scientific_name": "Thryomanes bewickii", "common_name": "Bewick's Wren",
     "description": "a song of buzzy and clear notes ending in a musical, descending trill",
     "vocalization": "song"},

    # ── Thrushes, chats & Old World flycatchers ───────────────────────────
    {"scientific_name": "Turdus pilaris", "common_name": "Fieldfare",
     "description": "a hard, chuckling, laughing 'chack-chack-chack'",
     "vocalization": "call"},
    {"scientific_name": "Turdus iliacus", "common_name": "Redwing",
     "description": "a thin, drawn-out, high 'seeeih' flight call",
     "vocalization": "call"},
    {"scientific_name": "Turdus viscivorus", "common_name": "Mistle Thrush",
     "description": "far-carrying, wild, fluty phrases sung defiantly in stormy weather",
     "vocalization": "song"},
    {"scientific_name": "Catharus ustulatus", "common_name": "Swainson's Thrush",
     "description": "an upward-spiraling cascade of flute-like notes rising in pitch",
     "vocalization": "song"},
    {"scientific_name": "Ficedula hypoleuca", "common_name": "European Pied Flycatcher",
     "description": "a simple, rhythmic alternation of two clear notes: 'tree-tree-tree-chwee'",
     "vocalization": "song"},
    {"scientific_name": "Phoenicurus ochruros", "common_name": "Black Redstart",
     "description": "a short warble interrupted by a strange, crackling, gravelly rattle like crushed gravel",
     "vocalization": "song"},
    {"scientific_name": "Copsychus saularis", "common_name": "Oriental Magpie-Robin",
     "description": "a varied, melodious, whistling song delivered from a high perch",
     "vocalization": "song"},

    # ── Mimids, starlings, mynas ──────────────────────────────────────────
    {"scientific_name": "Acridotheres tristis", "common_name": "Common Myna",
     "description": "a rambling jumble of gurgles, chatters, and repeated squeaky notes",
     "vocalization": "song"},
    {"scientific_name": "Gracula religiosa", "common_name": "Common Hill Myna",
     "description": "astonishingly clear, loud, human-like whistles, squawks, and gurgles",
     "vocalization": "any"},
    {"scientific_name": "Toxostoma curvirostre", "common_name": "Curve-billed Thrasher",
     "description": "a sharp, liquid, whistled 'whit-wheet'",
     "vocalization": "call"},

    # ── Old World warblers ────────────────────────────────────────────────
    {"scientific_name": "Phylloscopus sibilatrix", "common_name": "Wood Warbler",
     "description": "an accelerating series of 'sip' notes running into a shivering, silvery trill",
     "vocalization": "song"},
    {"scientific_name": "Sylvia communis", "common_name": "Common Whitethroat",
     "description": "a short, hurried, scratchy warble thrown out in a dancing song-flight",
     "vocalization": "song"},
    {"scientific_name": "Sylvia borin", "common_name": "Garden Warbler",
     "description": "an even, mellow, sustained babbling warble with no clear structure",
     "vocalization": "song"},
    {"scientific_name": "Cettia cetti", "common_name": "Cetti's Warbler",
     "description": "a sudden, loud, explosive burst of rich notes erupting from dense cover",
     "vocalization": "song"},
    {"scientific_name": "Hippolais polyglotta", "common_name": "Melodious Warbler",
     "description": "a fast, sustained, chattering babble mixing sweet whistles and harsh notes",
     "vocalization": "song"},

    # ── New World warblers ────────────────────────────────────────────────
    {"scientific_name": "Setophaga striata", "common_name": "Blackpoll Warbler",
     "description": "an extremely high, thin, even series of 'tsit' notes swelling then fading",
     "vocalization": "song"},
    {"scientific_name": "Setophaga coronata", "common_name": "Yellow-rumped Warbler",
     "description": "a loose, musical trill that rises or falls slightly toward the end",
     "vocalization": "song"},
    {"scientific_name": "Parkesia noveboracensis", "common_name": "Northern Waterthrush",
     "description": "a loud, ringing series of emphatic chips accelerating and dropping in pitch",
     "vocalization": "song"},
    {"scientific_name": "Cardellina pusilla", "common_name": "Wilson's Warbler",
     "description": "a rapid, chattering series of 'chi-chi-chi' notes dropping at the end",
     "vocalization": "song"},

    # ── Tits & nuthatches ─────────────────────────────────────────────────
    {"scientific_name": "Baeolophus bicolor", "common_name": "Tufted Titmouse",
     "description": "a clear, whistled, repeated 'peter-peter-peter'",
     "vocalization": "song"},
    {"scientific_name": "Poecile carolinensis", "common_name": "Carolina Chickadee",
     "description": "a fast, high, four-note whistle and a rapid 'chick-a-dee-dee-dee'",
     "vocalization": "any"},
    {"scientific_name": "Periparus ater", "common_name": "Coal Tit",
     "description": "a high, repeated, bicycle-pump 'see-too, see-too, see-too'",
     "vocalization": "song"},
    {"scientific_name": "Aegithalos caudatus", "common_name": "Long-tailed Tit",
     "description": "a thin, rolling, trilled 'tsirrup' mixed with high 'see-see-see' contact notes",
     "vocalization": "call"},
    {"scientific_name": "Sitta canadensis", "common_name": "Red-breasted Nuthatch",
     "description": "a slow, nasal, tin-trumpet 'yank-yank', higher and more nasal than its relatives",
     "vocalization": "call"},

    # ── Corvids ───────────────────────────────────────────────────────────
    {"scientific_name": "Corvus corone", "common_name": "Carrion Crow",
     "description": "a harsh, flat, repeated 'kraa-kraa-kraa'",
     "vocalization": "call"},
    {"scientific_name": "Corvus monedula", "common_name": "Western Jackdaw",
     "description": "a sharp, metallic, abrupt 'kya' or 'jack'",
     "vocalization": "call"},
    {"scientific_name": "Corvus frugilegus", "common_name": "Rook",
     "description": "a higher, more nasal, drawn-out 'kaaah' than a crow",
     "vocalization": "call"},
    {"scientific_name": "Cyanocitta stelleri", "common_name": "Steller's Jay",
     "description": "a harsh, descending, scolding 'shaack-shaack-shaack'",
     "vocalization": "call"},
    {"scientific_name": "Aphelocoma californica", "common_name": "California Scrub-Jay",
     "description": "a rising, raspy, scratchy, scolding 'shreeenk'",
     "vocalization": "call"},

    # ── Sparrows, finches, buntings, icterids ─────────────────────────────
    {"scientific_name": "Passer domesticus", "common_name": "House Sparrow",
     "description": "a monotonous series of cheerful, chirping 'cheep' and 'chirrup' notes",
     "vocalization": "call"},
    {"scientific_name": "Sturnella magna", "common_name": "Eastern Meadowlark",
     "description": "a clear, plaintive, slurred whistle: 'spring-of-the-YEAR'",
     "vocalization": "song"},
    {"scientific_name": "Xanthocephalus xanthocephalus", "common_name": "Yellow-headed Blackbird",
     "description": "a strangled, grating, mechanical buzz like a rusty hinge being forced",
     "vocalization": "song"},
    {"scientific_name": "Quiscalus mexicanus", "common_name": "Great-tailed Grackle",
     "description": "a wild cacophony of harsh clucks, sweet whistles, and mechanical screeches",
     "vocalization": "any"},
    {"scientific_name": "Passerculus sandwichensis", "common_name": "Savannah Sparrow",
     "description": "a buzzy, insect-like 'tsip-tsip-tseeee-tsaay'",
     "vocalization": "song"},
    {"scientific_name": "Melospiza georgiana", "common_name": "Swamp Sparrow",
     "description": "a slow, sweet, musical trill on one pitch",
     "vocalization": "song"},
    {"scientific_name": "Spinus pinus", "common_name": "Pine Siskin",
     "description": "a rising, buzzy, ascending 'zzzreeee' like a drawn-out question",
     "vocalization": "call"},
    {"scientific_name": "Acanthis flammea", "common_name": "Common Redpoll",
     "description": "a dry, rattling 'chit-chit-chit' interspersed with a buzzy trill",
     "vocalization": "call"},

    # ── Vireos, tanagers, grosbeaks ───────────────────────────────────────
    {"scientific_name": "Vireo gilvus", "common_name": "Warbling Vireo",
     "description": "a lazy, rambling warble that rises to an emphatic note at the very end",
     "vocalization": "song"},
    {"scientific_name": "Piranga ludoviciana", "common_name": "Western Tanager",
     "description": "a hoarse, burry, robin-like caroling delivered in short, rough phrases",
     "vocalization": "song"},
    {"scientific_name": "Pheucticus melanocephalus", "common_name": "Black-headed Grosbeak",
     "description": "a rich, rising-and-falling, robin-like warble, sweeter and more fluid",
     "vocalization": "song"},
    {"scientific_name": "Passerina ciris", "common_name": "Painted Bunting",
     "description": "a sweet, musical, continuous warble of clear, slightly metallic notes",
     "vocalization": "song"},

    # ── Australasian ──────────────────────────────────────────────────────
    {"scientific_name": "Cracticus nigrogularis", "common_name": "Pied Butcherbird",
     "description": "exquisite, pure, flute-like piping phrases, often delivered at dawn",
     "vocalization": "song"},
    {"scientific_name": "Cracticus torquatus", "common_name": "Gray Butcherbird",
     "description": "a rich, ringing, rollicking piping with harsh, chuckling notes mixed in",
     "vocalization": "song"},
    {"scientific_name": "Colluricincla harmonica", "common_name": "Gray Shrikethrush",
     "description": "a rich, musical series of mellow notes ending in a sharp, upward 'pip-pip-hee-oh'",
     "vocalization": "song"},
    {"scientific_name": "Rhipidura leucophrys", "common_name": "Willie Wagtail",
     "description": "a chattering, scolding phrase often likened to 'sweet-pretty-creature'",
     "vocalization": "any"},
    {"scientific_name": "Malurus cyaneus", "common_name": "Superb Fairywren",
     "description": "a high, rapid, reeling trill of thin, tinkling notes",
     "vocalization": "song"},

    # ── African ───────────────────────────────────────────────────────────
    {"scientific_name": "Bostrychia hagedash", "common_name": "Hadada Ibis",
     "description": "a loud, raucous, far-carrying 'ha-ha-ha-de-dah'",
     "vocalization": "call"},
    {"scientific_name": "Streptopelia semitorquata", "common_name": "Red-eyed Dove",
     "description": "a rhythmic six-note coo like 'I-AM-a-red-eyed-dove'",
     "vocalization": "song"},

    # ── Asian ─────────────────────────────────────────────────────────────
    {"scientific_name": "Pycnonotus jocosus", "common_name": "Red-whiskered Bulbul",
     "description": "a cheerful, sharp, lilting phrase rendered 'kink-a-joo'",
     "vocalization": "song"},
    {"scientific_name": "Copsychus malabaricus", "common_name": "White-rumped Shama",
     "description": "a rich, varied, melodious cascade of clear, ringing whistled phrases",
     "vocalization": "song"},

    # ── Amphibians (famous voices) ────────────────────────────────────────
    {"scientific_name": "Pseudacris regilla", "common_name": "Pacific Chorus Frog",
     "description": "a loud, two-parted 'ribbit' — the archetypal frog sound",
     "vocalization": "call"},
    {"scientific_name": "Lithobates clamitans", "common_name": "Green Frog",
     "description": "a single, abrupt, plucked-banjo-string 'gunk'",
     "vocalization": "call"},
]
